# Sqlite3 Settings
sqlite3: &sqlite3
  adapter: sqlite3
  pool: 5
  timeout: 5000

# Mysql Settings
mysql: &mysql
  adapter: mysql
  encoding: utf8
  username: root
  password:
  pool: 5

development:
  <<: *sqlite3
  database: db/development.sqlite3
  # <<: *mysql
  # database: conductor_development

test:
  <<: *sqlite3
  database: db/test.sqlite3
  # <<: *mysql
  # database: conductor_test

staging:
  <<: *sqlite3
  database: db/staging.sqlite3
  # <<: *mysql
  # database: conductor
  
production:
  <<: *sqlite3
  database: db/production.sqlite3
  # <<: *mysql
  # database: conductor
